services:
  api:
    build: .
    container_name: cinema-api
    ports:
      - "8080:8080"
    environment:
      - REDIS_URL=redis://redis:6379
      - HOLD_TTL_SECONDS=120
    depends_on:
      redis:
        condition: service_healthy

  redis:
    container_name: redis
    image: redis:7-alpine
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 2s
      timeout: 2s
      retries: 15
